export const authConstants = {
    LOGIN_REQUEST: "LOGIN_REQUEST",
    LOGIN_FAILURE: "LOGIN_FAILURE",
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    LOGOUT_REQUEST: "LOGOUT_REQUEST"
};

export const userConstants = {
    USER_REGISTER_REQUEST: "USER_REGISTER_REQUEST",
    USER_REGISTER_FAILURE: "USER_REGISTER_FAILURE",
    USER_REGISTER_SUCCESS: "USER_REGISTER_SUCCESS"
}

export const blogConstants = {
    BLOG_CREATE_REQUEST: "BLOG_CREATE_REQUEST",
    BLOG_CREATE_FAILURE: "BLOG_CREATE_FAILURE",
    BLOG_CREATE_SUCCESS: "BLOG_CREATE_SUCCESS",

    BLOG_READ_REQUEST: "BLOG_READ_REQUEST",
    BLOG_READ_FAILURE: "BLOG_READ_FAILURE",
    BLOG_READ_SUCCESS: "BLOG_READ_SUCCESS",

    BLOG_UPDATE_REQUEST: "BLOG_UPDATE_REQUEST",
    BLOG_UPDATE_FAILURE: "BLOG_UPDATE_FAILURE",
    BLOG_UPDATE_SUCCESS: "BLOG_UPDATE_SUCCESS",

    BLOG_DELETE_REQUEST: "BLOG_DELETE_REQUEST",
    BLOG_DELETE_FAILURE: "BLOG_DELETE_FAILURE",
    BLOG_DELETE_SUCCESS: "BLOG_DELETE_SUCCESS"
}